apiVersion: chaitu.backstage.io/v1alpha1
kind: Template
metadata:
  name: artist-web
  description: The place to be, for great artists
spec:
  type: service
  owner: artist-relations-team
  
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: Hello 
